### PR TITLE
add link with g++ in makefile

### PR DESCRIPTION
**Pull request by data2path**
Hi,

Removed all g++ compilation issues changes.
Link with g++ in makefile. Build working on linux and cygwin
Was not able build with cmake on cygwin.

Test results on linux: 20 pass, 0 fail
Test results on cygwin: 16 pass, 4 fail

Toolame tests conditions:
Cygwin 2.2.1, gcc 4.9.3
Ubuntu 14.04, gcc 4.8.4
20 tests : 
-b 32 -s 48, …, -b 384 -s 48, 
-b 256 -y -1 -s 48, …, -b 256, -y 4 -s 48

Toolame method of test :
convert a wav file to mp2 with Toolame on Cygwin or Ubuntu and compare mp2 binary files before changes.

toolame -b 112 -s 48 in.wav out.mp2
out_file_-b_112_-s_48

toolame -b 320 -s 48 in.wav out.mp2
out_file_-b_320_-s_48_1
out_file_-b_320_-s_48_2

toolame -b 256 -y 2 -s 48 in.wav out.mp2
out_file_-b_256_-y_2_-s_48_1
out_file_-b_256_-y_2_-s_48_2

toolame -b 256 -y 3 -s 48 in.wav out.mp2
out_file_-b_256_-y_3_-s_48

### CODE REVIEW

**Comment by mpbraendli** [comment]
@mnhauke do you have an explanation why compilation could fail on cygwin ?
I would prefer that we fix the CMakeLists instead...

**Comment by mnhauke** [comment]
i just did a quick test on a cygwin64 installation and cannot reproduce the linking issue when building with cmake.
@data2path please provide logs with detailed error messages


here are some instructions on how to build on toolame-dab on cygwin64
```
#### download cygwin (64bit)
http://cygwin.com/setup-x86_64.exe
# copy cygwin setup.exe to %USERPROFILE%\Downloads\cygwin\
# run setup with default package selection
cd %USERPROFILE%\Downloads\cygwin\
setup-x86_64.exe

# install common packages:
cd  %USERPROFILE%\Downloads\cygwin64\
setup-x86_64.exe -q --packages "git,patch"

# build stuff in ~/tmp/
mkdir ~/tmp/
cd tmp/

###  Base devel
setup-x86_64.exe -q --packages "make,gcc-core,gcc-g++"
setup-x86_64.exe -q --packages "autoconf,automake,libtool"
setup-x86_64.exe -q --packages "pkg-config"
setup-x86_64.exe -q --packages "cmake"
setup-x86_64.exe -q --packages "wget"

### libsodium
cd ~/tmp/
git clone https://github.com/jedisct1/libsodium.git
cd libsodium
autoreconf -fiv
./configure
make
make install


### libzmq
# requirements:
# - libsodium
cd ~/tmp/
git clone https://github.com/zeromq/libzmq.git
cd libzmq
autoreconf -fiv
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig
./configure
make
make install


### toolame-dab
# requirements:
# - zmq
cd ~/tmp/
git clone https://github.com/mnhauke/toolame-dab
cd toolame-dab
mkdir build
cd build
wget https://github.com/Opendigitalradio/toolame-dab/pull/9.patch
patch -p1 < 9.patch
export LDFLAGS=-L/usr/local/lib
cmake ..
make
make install


### optional: copy binaries and libs outside cygwin (e.g. the current users Desktop folder toolame-bin)
export TOOLAME_BINDIR="$USERPROFILE/Desktop/toolame-bin/"
mkdir -p $TOOLAME_BINDIR
cp \
  /usr/local/bin/toolame-dab.exe \
  /usr/bin/cygwin1.dll \
  /usr/bin/cyggcc_s-seh-1.dll \
  /usr/bin/cygstdc++-6.dll \
  /usr/local/bin/cygsodium-13.dll \
  /usr/local/bin/cygzmq.dll \
  $TOOLAME_BINDIR
```

**Comment by data2path** [comment]
Thanks mnhauke, for cmake I missed the PKG_CONFIG_PATH and LDFLAGS.
Now compilation is ok but have link errors with libzmq because g++ need to be used for link instead of gcc. I am using cygwin32 2.2.1. So it seems that with cygwin64 you don't need g++ to link toolame with libzmq, isn't it ?

**Comment by mnhauke** [comment]
The following steps are working fine in a fresh installed cygwin32 environment.
@data2path can you please provide logs (output from "make VERBOSE=1") with the linking error
```
#### download cygwin (32bit)
http://cygwin.com/setup-x86.exe
# copy cygwin setup.exe to %USERPROFILE%\Downloads\cygwin32\
# run setup with default package selection
cd %USERPROFILE%\Downloads\cygwin32\
setup-x86.exe

# cygwin version:
$ uname -a
CYGWIN_NT-6.1-WOW Win7Pro 2.2.1(0.289/5/3) 2015-08-20 11:40 i686 Cygwin


# install common packages:
cd  %USERPROFILE%\Downloads\cygwin32\
setup-x86.exe -q --packages "git,patch"

# build stuff in ~/tmp/
mkdir ~/tmp/
cd tmp/

###  Base devel
setup-x86.exe -q --packages "make,gcc-core,gcc-g++"
setup-x86.exe -q --packages "autoconf,automake,libtool"
setup-x86.exe -q --packages "pkg-config"
setup-x86.exe -q --packages "cmake"
setup-x86.exe -q --packages "wget"

### libsodium
cd ~/tmp/
git clone https://github.com/jedisct1/libsodium.git
cd libsodium
autoreconf -fiv
./configure
make
make install


### libzmq
# requirements:
# - libsodium
cd ~/tmp/
git clone https://github.com/zeromq/libzmq.git
cd libzmq
autoreconf -fiv
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig
./configure
make
make install


### toolame-dab
# requirements:
# - zmq
cd ~/tmp/
git clone https://github.com/mnhauke/toolame-dab
cd toolame-dab
wget https://github.com/Opendigitalradio/toolame-dab/pull/9.patch
patch -p1 < 9.patch
mkdir build
cd build
export LDFLAGS=-L/usr/local/lib
cmake ..
make
make install


### optional: copy binaries and libs outside cygwin (e.g. the current users Desktop folder toolame-bin-x86)
export TOOLAME_BINDIR="$USERPROFILE/Desktop/toolame-bin-x86/"
mkdir -p $TOOLAME_BINDIR
cp \
  /usr/local/bin/toolame-dab.exe \
  /usr/bin/cygwin1.dll \
  /usr/bin/cyggcc_s-1.dll \
  /usr/bin/cygstdc++-6.dll \
  /usr/local/bin/cygsodium-13.dll \
  /usr/local/bin/cygzmq.dll \
  $TOOLAME_BINDIR

```

**Comment by data2path** [comment]
Thanks for your help.

**Pull request closed without merging**
